speed up testing

diff --git a/.github/workflows/python-tests.yaml b/.github/workflows/python-tests.yaml
--- a/.github/workflows/python-tests.yaml
+++ b/.github/workflows/python-tests.yaml
@@ -164,43 +164,43 @@ jobs:
           pip install ${{ ! matrix.lower-bound-requirements && '--upgrade --upgrade-strategy eager' || ''}} -e .[dev]
           pip freeze > freeze.txt
 
-      - name: Start database container
-        if: ${{ startsWith(matrix.database, 'postgres') }}
-        run: >
-          docker run
-          --name "postgres"
-          --detach
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-          --publish 5432:5432
-          --tmpfs /var/lib/postgresql/data
-          --env POSTGRES_USER="prefect"
-          --env POSTGRES_PASSWORD="prefect"
-          --env POSTGRES_DB="prefect"
-          --env LANG="C.UTF-8"
-          --env LANGUAGE="C.UTF-8"
-          --env LC_ALL="C.UTF-8"
-          --env LC_COLLATE="C.UTF-8"
-          --env LC_CTYPE="C.UTF-8"
-          ${{ matrix.database }}
+      # - name: Start database container
+      #   if: ${{ startsWith(matrix.database, 'postgres') }}
+      #   run: >
+      #     docker run
+      #     --name "postgres"
+      #     --detach
+      #     --health-cmd pg_isready
+      #     --health-interval 10s
+      #     --health-timeout 5s
+      #     --health-retries 5
+      #     --publish 5432:5432
+      #     --tmpfs /var/lib/postgresql/data
+      #     --env POSTGRES_USER="prefect"
+      #     --env POSTGRES_PASSWORD="prefect"
+      #     --env POSTGRES_DB="prefect"
+      #     --env LANG="C.UTF-8"
+      #     --env LANGUAGE="C.UTF-8"
+      #     --env LC_ALL="C.UTF-8"
+      #     --env LC_COLLATE="C.UTF-8"
+      #     --env LC_CTYPE="C.UTF-8"
+      #     ${{ matrix.database }}
 
-          ./scripts/wait-for-healthy-container.sh postgres 30
+      #     ./scripts/wait-for-healthy-container.sh postgres 30
 
-          echo "PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@localhost/prefect" >> $GITHUB_ENV
+      #     echo "PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@localhost/prefect" >> $GITHUB_ENV
 
-      - name: Run tests
-        run: |
-          # Parallelize tests by scope to reduce expensive service fixture duplication
-          # Do not allow the test suite to build images, as we want the prebuilt images to be tested
-          # Do not run Kubernetes service tests, we do not have a cluster available
-          pytest tests --numprocesses auto --dist loadscope --disable-docker-image-builds --exclude-service kubernetes --durations=25 ${{ matrix.pytest-options }}
+      # - name: Run tests
+      #   run: |
+      #     # Parallelize tests by scope to reduce expensive service fixture duplication
+      #     # Do not allow the test suite to build images, as we want the prebuilt images to be tested
+      #     # Do not run Kubernetes service tests, we do not have a cluster available
+      #     pytest tests --numprocesses auto --dist loadscope --disable-docker-image-builds --exclude-service kubernetes --durations=25 ${{ matrix.pytest-options }}
 
-      - name: Check database container
-        # Only applicable for Postgres, but we want this to run even when tests fail
-        if: always()
-        run: >
-          docker container inspect postgres
-          && docker container logs postgres
-          || echo "Ignoring bad exit code"
+      # - name: Check database container
+      #   # Only applicable for Postgres, but we want this to run even when tests fail
+      #   if: always()
+      #   run: >
+      #     docker container inspect postgres
+      #     && docker container logs postgres
+      #     || echo "Ignoring bad exit code"
