Fix pulling outputs into final step

diff --git a/.github/workflows/static-analysis.yaml b/.github/workflows/static-analysis.yaml
--- a/.github/workflows/static-analysis.yaml
+++ b/.github/workflows/static-analysis.yaml
@@ -83,7 +83,10 @@ jobs:
           python-version: "3.12"
 
       - name: Calculate type completeness score
+        id: calculate_current_score
         run: |
+          # `pyright` will exit with a non-zero status code if it finds any issues,
+          # so we need to explicitly ignore the exit code with `|| true`.
           uv tool run --with . pyright --verifytypes prefect --ignoreexternal --outputjson > prefect-analysis.json || true
           SCORE=$(jq -r '.typeCompleteness.completenessScore' prefect-analysis.json)
           echo "current_score=$SCORE" >> $GITHUB_OUTPUT
@@ -93,6 +96,7 @@ jobs:
           git checkout ${{ github.base_ref }}
 
       - name: Calculate base branch score
+        id: calculate_base_score
         run: |
           uv tool run --with . pyright --verifytypes prefect --ignoreexternal --outputjson > prefect-analysis-base.json || true
           BASE_SCORE=$(jq -r '.typeCompleteness.completenessScore' prefect-analysis-base.json)
@@ -100,11 +104,14 @@ jobs:
 
       - name: Compare scores
         run: |
-          if (( $(awk 'BEGIN {print ('$BASE_SCORE' > '$CURRENT_SCORE')}') )); then
+          CURRENT_SCORE=$(echo ${{ steps.calculate_current_score.outputs.current_score }})
+          BASE_SCORE=$(echo ${{ steps.calculate_base_score.outputs.base_score }})
+
+          if (( $(echo "$BASE_SCORE > $CURRENT_SCORE" | bc -l) )); then
             echo "❌ Type completeness score has decreased from $BASE_SCORE to $CURRENT_SCORE" >> $GITHUB_STEP_SUMMARY
             exit 1
-          elif (( $(awk 'BEGIN {print ('$BASE_SCORE' < '$CURRENT_SCORE')}') )); then
+          elif (( $(echo "$BASE_SCORE < $CURRENT_SCORE" | bc -l) )); then
             echo "✅ Type completeness score has increased from $BASE_SCORE to $CURRENT_SCORE" >> $GITHUB_STEP_SUMMARY
           else
-            echo "✅ Type completeness score has not changed from $BASE_SCORE to $CURRENT_SCORE" >> $GITHUB_STEP_SUMMARY
+            echo "✅ Type completeness score remained unchanged at $BASE_SCORE" >> $GITHUB_STEP_SUMMARY
           fi
